### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by ajinabraham** [chrislim2888/IP2Location-Python#15]
```
✗ pip install IP2Location
Requirement already satisfied: IP2Location in ./venv/lib/python3.8/site-packages (8.6.0)
(venv) ➜ ✗ python
Python 3.8.2 (default, Dec 21 2020, 15:06:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import IP2Location
>>> IP2LocObj = IP2Location.IP2Location()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../venv/lib/python3.8/site-packages/IP2Location.py", line 155, in __init__
    if os.path.isfile(filename) == False:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by chrislim2888** [comment]
Hi ajinabraham,

You should defined the database path when calling our library. Please refer to sample.py in the repository for the example.

**Comment by ajinabraham** [comment]
I suppose this is a breaking change then.

It used to be:
```
IP2LocObj = IP2Location.IP2Location()
IP2LocObj.open(bin_file)
```
on previous versions.

You might want to update the documentation here https://www.ip2location.com/development-libraries/ip2location/python
